/**
 * Share a Brief — shared utility for exporting Mapvest daily briefs and
 * research articles.
 *
 * Three entry points:
 *   • shareBriefText(...)  — clean paste-safe text via expo-sharing (with a
 *     react-native Share.share fallback). Always works.
 *   • shareBriefImage(...) — snapshots a React view to PNG via
 *     react-native-view-shot / expo-view-shot when available, then hands the
 *     file off to expo-sharing. Degrades gracefully to text when the
 *     view-shot library is not installed — we do NOT crash and we do NOT
 *     try to install a new dep at runtime.
 *   • shareResearchMemo(...) — downloads an authenticated research PDF and
 *     opens the native share sheet.
 *
 * Kept UI-free so callers (Home, ResearchSheet) can drive their own buttons.
 */

import { getDeviceId } from "@/util/deviceId";
import { API_URL } from "@/util/env";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";
import { Share } from "react-native";
import { MAPVEST_URL } from "./shareLinks";

export { MAPVEST_URL } from "./shareLinks";

/**
 * Format a date the way our shared cards want it — "Aug 6, 2026". We pass
 * `undefined` for locale so the OS picks the user's preferred locale but the
 * ordering stays month-day-year-ish across most Latin locales.
 */
function formatShareDate(d: Date = new Date()) {
  return d.toLocaleDateString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

export type ShareBriefTextInput = {
  headline: string;
  body: string;
  /** Optional ticker — prepends "$AAPL · Mapvest Daily" style header. */
  ticker?: string;
  /** Optional footer override; defaults to the canonical public Mapvest URL. */
  footer?: string;
};

/**
 * Build the paste-safe text block that ships with a share. No markdown, no
 * asterisks — just unicode punctuation (·, —) that survives Twitter, iMessage,
 * Slack, and email without any weird rendering. Line breaks are preserved.
 */
export function formatBriefText({ headline, body, ticker, footer }: ShareBriefTextInput): string {
  const header = ticker
    ? `$${ticker.replace(/^\$/, "").toUpperCase()} · Mapvest Daily`
    : "Mapvest Daily";
  const date = formatShareDate();
  const tail = footer ?? `— generated by Mapvest · ${MAPVEST_URL}`;
  // Two-line gaps between blocks so it reads like a card, not a wall of text.
  return `${header}\n${date}\n\n${headline.trim()}\n\n${body.trim()}\n\n${tail}`;
}

/**
 * Share the brief as clean formatted text. Prefers expo-sharing when
 * available (better UX on iOS — same sheet as PNG shares) but falls back to
 * the built-in RN Share.share, which is guaranteed to exist.
 *
 * We swallow the "user cancelled" case silently — sharing sheets return
 * quietly when dismissed, and there's nothing useful to tell the user.
 */
export async function shareBriefText(input: ShareBriefTextInput): Promise<void> {
  const message = formatBriefText(input);
  try {
    // expo-sharing.shareAsync only accepts file URIs — so for text we use the
    // RN Share.share API, which is the correct primitive for a text payload.
    await Share.share({ message });
  } catch {
    // Silently ignore — user cancel, or an unusual OS failure. We don't want
    // to spam an alert on cancellation.
  }
}

/** Download an owner-scoped research memo and hand the PDF to the native share sheet. */
export async function shareResearchMemo(memoUrl: string, token?: string): Promise<void> {
  const url = new URL(memoUrl, `${API_URL}/`);
  if (url.origin !== new URL(API_URL).origin) {
    throw new Error("Invalid research memo URL.");
  }
  if (!FileSystem.cacheDirectory) throw new Error("Memo storage is unavailable.");
  const headers: Record<string, string> = { Accept: "application/pdf" };
  if (token) headers.Authorization = `Bearer ${token}`;
  try {
    headers["X-Device-Id"] = await getDeviceId();
  } catch {
    /* Signed-in requests can still be authorized without a device id. */
  }
  const destination = `${FileSystem.cacheDirectory}mapvest-research-${Date.now()}.pdf`;
  const result = await FileSystem.downloadAsync(url.toString(), destination, { headers });
  if (result.status < 200 || result.status >= 300) {
    throw new Error(`Memo download failed (${result.status}).`);
  }
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(result.uri, {
      mimeType: "application/pdf",
      UTI: "com.adobe.pdf",
      dialogTitle: "Open research memo",
    });
    return;
  }
  await Share.share({ url: result.uri });
}

/**
 * Try to snapshot a React ref to PNG and share it. Falls back to text share
 * when no view-shot library is installed (we do not want to add a runtime
 * dependency without an explicit install).
 *
 * `viewRef` should be a ref pointing at a React Native <View> — usually the
 * one wrapping ShareBriefCard.
 *
 * `filename` is the download name suggestion (e.g. "mapvest-brief-AAPL.png").
 * We sanitize it before use.
 *
 * `textFallback` is the text used if the view-shot library isn't available.
 * Callers should always pass this so degradation is silent to the user.
 */
export async function shareBriefImage(
  viewRef: React.RefObject<unknown> | null,
  filename: string,
  textFallback: ShareBriefTextInput,
): Promise<void> {
  // Dynamic require so bundlers/metro don't try to resolve at build time —
  // matches the "degrade gracefully if not installed" contract.
  type CaptureRefFn = (ref: unknown, opts?: Record<string, unknown>) => Promise<string>;
  let captureRef: CaptureRefFn | null = null;
  try {
    // Try the community-maintained package first (most common).
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const mod = require("react-native-view-shot") as {
      captureRef?: CaptureRefFn;
    };
    if (typeof mod.captureRef === "function") captureRef = mod.captureRef;
  } catch {
    // not installed — try the expo-scoped alias
  }
  if (!captureRef) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const mod = require("expo-view-shot") as {
        captureRef?: CaptureRefFn;
      };
      if (typeof mod.captureRef === "function") captureRef = mod.captureRef;
    } catch {
      // still not installed
    }
  }

  if (!captureRef || !viewRef?.current) {
    // No snapshot library installed OR ref not yet attached — fall back to
    // text so the user still gets something out of tapping Share.
    if (__DEV__) {
      // eslint-disable-next-line no-console
      console.info("[share] view-shot not available — falling back to text share");
    }
    return shareBriefText(textFallback);
  }

  try {
    const uri = await captureRef(viewRef.current, {
      format: "png",
      quality: 1,
      result: "tmpfile",
      // fileName gets ignored on iOS but respected on Android — safe to pass.
      fileName: filename.replace(/[^\w.-]+/g, "_"),
    });
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri, {
        mimeType: "image/png",
        UTI: "public.png",
        dialogTitle: "Share Mapvest brief",
      });
    } else {
      // No sharing sheet — fall back to text so the tap isn't a dead-end.
      await shareBriefText(textFallback);
    }
  } catch {
    // Snapshot itself failed (off-screen view, GL surface issues, etc.) —
    // silently fall back to text so the share button is never "broken".
    await shareBriefText(textFallback);
  }
}
